apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align: center;">
        <h1>Pizza Time!</h1>
        <p>who dat? idk $(ENV)</p>
      </body>
    </html>
