apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align: center;">
        <h1>🚀 Hello from Argo CD ApplicationSet!</h1>
        <p>This page was deployed automatically via ApplicationSet.</p>
      </body>
    </html>
