apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yml
  - service.yml
  - configmap.yml
  - ingress.yml

replacements:
  - source:
      kind: ConfigMap
      name: html-content
      fieldPath: metadata.annotations.env
    targets:
      - select:
          kind: ConfigMap
          name: html-content
        fieldPaths:
          - data.index.html
